services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: saam_admin
      POSTGRES_PASSWORD: admin123@
      POSTGRES_DB: employee_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: employee-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_management
      SPRING_DATASOURCE_USERNAME: saam_admin
      SPRING_DATASOURCE_PASSWORD: admin123@
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SERVER_PORT: 8080
      SPRING_FLYWAY_ENABLED: true
    depends_on:
      - postgres

volumes:
  postgres_data:

